CREATE TABLE players (
    id INT AUTO_INCREMENT PRIMARY KEY,
    uuid VARCHAR(36) NOT NULL UNIQUE,
    name VARCHAR(16) NOT NULL,
    x FLOAT NOT NULL,
    y FLOAT NOT NULL,
    z FLOAT NOT NULL,
    world VARCHAR(32) NOT NULL,
    health INT NOT NULL DEFAULT 20,
    exp INT NOT NULL DEFAULT 0,
    inventory JSON NOT NULL, -- アイテムの個数もJSONで管理
    last_login TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
